name: cmc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip

  # Données météo
  - herbie-data
  - cfgrib
  - eccodes
  - python-eccodes

  # Données / calcul
  - xarray
  - numpy
  - pandas
  - pyarrow          # nécessaire pour lire/écrire les fichiers Parquet
  - scipy

  # Géospatial
  - cartopy
  - pyproj
  - shapely

  # Visualisation
  - matplotlib
  - metpy

  # Utilitaires
  - requests
  - pooch
  - jupyter
  - ipykernel
